#ifndef FB_MELODIES_VERIFIER_H
#define FB_MELODIES_VERIFIER_H

/* Generated by flatcc 0.6.1 FlatBuffers schema compiler for C by dvide.com */

#ifndef FB_MELODIES_READER_H
#include "fb_melodies_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int melodies_Tone_verify_table(flatcc_table_verifier_descriptor_t *td);
static int melodies_Melody_verify_table(flatcc_table_verifier_descriptor_t *td);

static int melodies_Tone_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 4, 4) /* frequency */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* duration */)) return ret;
    return flatcc_verify_ok;
}

static inline int melodies_Tone_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, melodies_Tone_identifier, &melodies_Tone_verify_table);
}

static inline int melodies_Tone_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, melodies_Tone_type_identifier, &melodies_Tone_verify_table);
}

static inline int melodies_Tone_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &melodies_Tone_verify_table);
}

static inline int melodies_Tone_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &melodies_Tone_verify_table);
}

static int melodies_Melody_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* label */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 1, 0, &melodies_Tone_verify_table) /* tones */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 4, 4) /* speed */)) return ret;
    return flatcc_verify_ok;
}

static inline int melodies_Melody_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, melodies_Melody_identifier, &melodies_Melody_verify_table);
}

static inline int melodies_Melody_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, melodies_Melody_type_identifier, &melodies_Melody_verify_table);
}

static inline int melodies_Melody_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &melodies_Melody_verify_table);
}

static inline int melodies_Melody_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &melodies_Melody_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* FB_MELODIES_VERIFIER_H */
